# Generated by Django 6.0.5 on 2026-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_breed_color_egglog_updated_at_alter_hen_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hens/'),
        ),
    ]
